app/models/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

from app import db, login_manager


class User(UserMixin, db.Model):
    """
    Create a table for the workers
    """

    # Ensures table will be named in plural and not in singular
    # as is the name of the model
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    first_name = db.Column(db.String(60), index=True)
    last_name = db.Column(db.String(60), index=True)
    image_file = db.Column(db.String(60), nullable=False, default='default.jpg')
    phone_no = db.Column(db.String(12), unique=True)
    password_hash = db.Column(db.String(128))
    employment_status = db.Column(db.String())
    worker_description = db.Column(db.String())
    job = db.relationship('Job', backref='user', lazy=True)
    review = db.relationship('Review', backref='user', lazy=True)


    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<Worker: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# jobs table
class Job(db.Model):

    __tablename__ = 'jobs'
    jobs_id = db.Column(db.Integer, primary_key=True)
    job_title = db.Column(db.String(60), index=True)
    date_posted = db.Column(db.DateTime, nullable=False, default = datetime.utcnow)
    job_description = db.Column(db.Text, nullable=False)
    job_category = db.Column(db.String, nullable=False)
    location = db.Column(db.String(60), index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'),nullable=False)

    def __repr__(self):
        return '<Job: {}>'.format(self.job_description)

class Review(db.Model):

    __tablename__ = 'reviews'


    review_id = db.Column(db.Integer, primary_key=True)
    rate = db.Column(db.Integer)
    comment = db.Column(db.Text)
    username = db.Column(db.String(60))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return '<Review: {}>'.format(self.comment)

app/job/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError,TextAreaField, DateField, SelectField
from wtforms.validators import DataRequired, Length
from datetime import date


class PostJob(FlaskForm):
    job_title = StringField('Job Title', validators=[DataRequired()])
    location = StringField('Location', validators=[DataRequired()])
    category = SelectField('Job Category', choices=[('househelp','Domestic Work'),('coding','Software Developemt'),('coding','Construction'),('coding','Software Developemt'),('coding','Software Developemt'),('coding','Software Developemt')], validators=[DataRequired()])
    date = DateField('Date Posted', default = date.today(), format='%d/%m/%Y')
    jd = TextAreaField('Job Description', validators=[DataRequired()])
    submit = SubmitField('Post Job')

class ReviewForm(FlaskForm):
    username = StringField('User You want to Review', validators=[DataRequired()])
    rating = SelectField('Rating', choices=[('0', '0'),('1', '1'),('2', '2'),('3', '3'),('4', '4'),('5', '5')])
    comment = TextAreaField('Comment about the Worker', validators=[DataRequired()])
    submit = SubmitField('Review')

class ApplyJob(FlaskForm):
    receiver = StringField('To', validators=[DataRequired()])
    sender = StringField('FROM', validators=[DataRequired()])
    subject = StringField('Subject', validators=[DataRequired()])
    message = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('SEND')
    

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
import os

#local imports
from config import app_config

#db variable initialization
db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(app_config['development'])
    db.init_app(app)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    migrate = Migrate(app, db)
    Bootstrap(app)
    from app.models import models
    login_manager.init_app(app)
    login_manager.login_message = 'You must be logged in to access this page.'
    login_manager.login_view = 'auth.login'
    from app.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    from app.job import job as job_blueprint
    app.register_blueprint(job_blueprint)

    
    return app

app/job/__init__.py
from flask import Blueprint

job = Blueprint('job', __name__)

from . import views

app/job/views.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user, login_required

from . import job
from .forms import PostJob, ReviewForm
from ..models.models import Job, User, Review
from app import db


@job.route('/post-job', methods=['GET','POST'])
def post_job():
    form = PostJob()
    if form.validate_on_submit():
        job = Job(
            job_title = form.job_title.data,
            date_posted = form.date.data,
            location = form.location.data,
            job_description = form.jd.data,
            job_category = form.category.data,
            user_id = current_user.id
        )
        db.session.add(job)
        db.session.commit()
        return redirect(url_for('job.all_jobs'))
    return render_template('post_job.html', form = form)

@job.route('/all-jobs')
@login_required
def all_jobs():
    jobs = Job.query.all()
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('jobs.html', jobs=jobs, image_file=image_file)

@job.route('/workers/<username>/review', methods=['GET','POST'])
@login_required
def review(username):
    user= User.query.filter_by(username = username).first_or_404()
    form = ReviewForm()
    if form.validate_on_submit():
        review = Review(
            username = form.username.data,
            rate = form.rating.data,
            comment = form.comment.data,
            user_id = current_user.id
        )
        db.session.add(review)
        db.session.commit()
        return redirect(url_for('job.user', username = username))
    return render_template('review.html', form=form, user = user)

@job.route('/workers/')
def workers():
    workers = User.query.all()
    return render_template('workers.html', workers=workers)

@job.route('/workers/<username>')
def user(username):
    sum = 0
    count = 0
    average = 0 
    user= User.query.filter_by(username = username).first_or_404()
    reviews = Review.query.filter_by(username=username).all()
    #getting average of the ratings
    for review in reviews:
        if review.rate:
            sum = sum + review.rate
            count += 1
            average = sum//count
        else:
            average
    
    return render_template('user.html', user = user, reviews = reviews, average =average, count = count)

@job.route('/delete/<int:jobs_id>', methods = ['GET','POST'])
@login_required
def delete(jobs_id):
    job = Job.query.get_or_404(jobs_id)
    db.session.delete(job)
    db.session.commit()
    flash('Your Job has been deleted successfully')
    return redirect(url_for('job.all_jobs'))

app/templates/account.html
{% extends 'base.html' %} {% block head %} {% endblock %}
<!-- import flask boostrap -->
{% import 'bootstrap/wtf.html' as wtf %}
<!-- flash message -->
{% import 'bootstrap/utils.html' as utils %} {% block content %}
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<div class="content-section">
  {{ utils.flashed_messages() }}
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}" />
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
      <p class="text-secondary">{{ current_user.phone_no }}</p>
    </div>
  </div>
  <h1>ACCOUNT INFO</h1>
  {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/apply.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
<!-- utils import -->
{% import'bootstrap/utils.html' as utils %}

<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}
<!-- Modal Content -->
<br />
<br />
<br />
<br />
<br />
<br />
<div>
  {{ utils.flashed_messages() }}
  <div class="content-section">
    <h1>APPLY FOR JOB</h1>
    <div class="container">
      {{ wtf.quick_form(form) }}
    </div>
  </div>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- local css -->
    <link
      href="{{ url_for('static', filename='main.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- semantic-ui -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
    />
    <!-- lato font -->
    <link
      href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap"
      rel="stylesheet"
    />
    <!-- Roboto font -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:900i&display=swap&subset=greek"
      rel="stylesheet"
    />
    <!-- GreatVibes -->

    <link
      href="https://fonts.googleapis.com/css?family=Cinzel:400,700&display=swap"
      rel="stylesheet"
    />

    <!-- font awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- js link -->
    <!-- mdnbootstrap -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/css/mdb.min.css"
    />

    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/js/mdb.min.js"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='main.js' )}}"
    ></script>

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />

    <title>Pata-Job</title>
  </head>
  <body>
    
    <div id="navbar">
      <a href="#default" id="logo">PATAJOB</a>
      <div id="navbar-left">
        <a class="active" href="{{ url_for('auth.index') }}" id="link-home"
          >Home</a
        >
      </div>
      <div id="navbar-right">
        {% if not current_user.is_authenticated%}
        <a href="{{ url_for('auth.login') }}" id="link-login">Login</a>
        <a href="{{ url_for('auth.register') }}" id="link-signup">SignUp</a>
        {% else %}
        <a href="{{ url_for('job.workers') }}" id="link-login">Workers</a>
        <a href="{{ url_for('job.all_jobs') }}" id="link-login">JOBS</a>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="user"
              ><i class="fa fa-user"></i> Hi, {{ current_user.username
              }}</i></a
            >
            <div class="dropdown-menu dropdown-menu-right" >
              <a href="{{ url_for('auth.account')}}" class="dropdown-item" style="color: black">Profile</a>
              <a href="{{ url_for('job.post_job') }}" class="dropdown-item" style="color: black">Post Job</a>
              <div class="dropdown-divider"></div>
              <a href="{{ url_for('auth.logout') }}" class="dropdown-item" style="color: black">Logout</a>
            </div>
            
          </li>
        </ul>
      
        {% endif %}
      </div>
    </div>
    {% block content %} {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}
<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}
<div class="home-main">
  <div class="home-section">
    <h1 id="welcome">
      Have you been wasting time looking for a Hustle? <br />Your dream Job is a
      click away. <br />
      Try us today.
    </h1>

    <a class="register" href="{{ url_for('auth.login') }}">LOGIN</a>
    <a class="login" href="{{ url_for('job.all_jobs') }}"
      >VIEW AVAILABLE JOBS</a
    >
  </div>
  <div class="container " style="height: 65vh">
    <h2 style="text-align: center; margin-top:285px">
      HOW PATAJOB APPLICATION WORK
    </h2>
    <!-- card one -->
    <div class="ui card">
      <div class="content">
        <div class="header">CREATE ACCOUNT</div>
      </div>
      <div class="content ">
        <i
          class="fa fa-sign-in about-icon"
          style="font-size: 50px;padding-left: 95px; color: #f19414"
        ></i>
        <h4 class="ui sub header">Activity</h4>
        <div class="ui small feed">
          <div class="event">
            <div class="content">
              <div class="summary">
                Create an Account in our website
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                Go ahead and login
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              You can go and search for a job or Post job
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- card two -->
    <div class="ui card" style="margin-left: 40px">
      <div class="content">
        <div class="header">SEARCH FOR JOB</div>
      </div>
      <div class="content">
        <i
          class="fa fa-search "
          style="font-size: 50px; padding-left: 95px; color: #f19414"
        ></i>
        <h4 class="ui sub header">Activity</h4>
        <div class="ui small feed">
          <div class="event">
            <div class="content">
              <div class="summary">
                <a>Elliot Fu</a> added <a>Jenny Hess</a> to the project
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                <a>Stevie Feliciano</a> was added as an <a>Administrator</a>
              </div>
            </div>
          </div>
          <div class="event"></div>
        </div>
      </div>
    </div>
    <!-- card three -->
    <div class="ui card" style="margin-left: 40px">
      <div class="content">
        <div class="header">CONTACT THE EMPLOYER</div>
      </div>
      <div class="content">
        <i
          class="fa fa-phone about-icon"
          style="font-size: 50px;padding-left: 95px; color: #f19414"
        ></i>
        <h4 class="ui sub header">Activity</h4>
        <div class="ui small feed">
          <div class="event">
            <div class="content">
              <div class="summary">
                <p>
                  Once we have Your Details on our website you can be contacted
                  by any employer
                </p>
              </div>
            </div>
          </div>

          <div class="event">
            <div class="content">
              <div class="summary"><a>Helen Troy</a> added two pictures</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer">
    <h3 style="text-align:center; padding-top: 75px">
      Contact us through our social media accounts
    </h3>
    <i
      class="fa fa-twitter "
      style="font-size: 50px; padding-left: 95px; color: #f19414; margin-left: 250px"
    ></i>
    <i
      class="fa fa-facebook "
      style="font-size: 50px; padding-left: 95px; color: #f19414"
    ></i>
    <i
      class="fa fa-instagram "
      style="font-size: 50px; padding-left: 95px; color: #f19414"
    ></i>
    <i
      class="fa fa-github "
      style="font-size: 50px; padding-left: 95px; color: #f19414"
    ></i>
    <i
      class="fa fa-linkedin "
      style="font-size: 50px; padding-left: 95px; color: #f19414"
    ></i>
    <p style="margin-top: 100px;margin-left: 500px">
      Copyrights &copy 2019 PATAJOB. All rights reserved
    </p>
  </div>
</div>

{% endblock %}

app/templates/jobs.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
<!-- flash messages -->
{% import 'bootstrap/utils.html' as utils %}

<!-- head -->
{% block head %} {% endblock %}

<!-- body -->

{% block content %}

<br />
<br />
<br />
<br />
<br />
<br />
<!-- search bar -->

{{ utils.flashed_messages() }}
<div style="background-color:#eaf2f2">
  <div class="container" style="float: right">
    <br />
    <div class="row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8">
        <form class="card card-sm">
          <div class="card-body row no-gutters align-items-center">
            <div class="col-auto">
              <i class="search icon"></i>
            </div>
            <!--end of col-->
            <div class="col">
              <input
                onkeyup="myFunction()"
                type="text"
                id="myInput"
                name=""
                class="form-control form-control-lg form-control-borderless"
                type="search"
                placeholder="Search Job title or Location"
              />
            </div>
            <!--end of col-->
            <div class="col-auto">
              <button
                class="btn btn-lg "
                style="background-color: #f19414;"
                type="submit"
              >
                Search
              </button>
            </div>
            <!--end of col-->
          </div>
        </form>
      </div>
      <!--end of col-->
    </div>
  </div>

  {% for job in jobs %}
  <div class="ui raised  card" style="width: 50%; margin-left: 20%">
    <div class="content">
      <div class="header">JOB TITLE: {{ job.job_title }}</div>
      <div class="meta">
        <span class="right floated time"></span>
        <span class="category">{{ job.job_categoty }}</span>
      </div>
      <div class="description">
        {{ job.job_description }}
      </div>
    </div>
    <div class="extra content">
      <div class="left floated">
        <span id="location">Location: {{ job.location }}</span>
        <span style="margin-left: 20px"
          >Employers Email: {{ job.user.email }}</span
        >
      </div>
      <div class="right floated author">
        {% if job.user.username == current_user.username %}
        <button
          class="btn btn-danger"
          style="margin-right: 40px"
          data-toggle="modal"
          data-target="#deleteModal"
        >
          DELETE
        </button>
        {% endif %}
        <img
          class="ui avatar image"
          src="{{ url_for('static', filename='profile_pics/' + job.user.image_file) }}"
        />
        {{ job.user.username }}
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="deleteModal"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="deleteModal" style="margin-left: 100px">
          ARE YOU SURE YOU WANT TO DELETE THIS JOB?
        </h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          Close
        </button>
        <form
          action="{{ url_for('job.delete', jobs_id=job.jobs_id) }}"
          method="POST"
        >
          <input class="btn btn-danger" type="submit" name="" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %} {% endblock %}

app/templates/login.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
<!-- flash messages -->
{% import 'bootstrap/utils.html' as utils %}

<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}

<!-- Modal Content -->
<div style="background-color: #eaf2f2; height:100vh">
  <div class="form-content">
    {{ utils.flashed_messages() }}
    <div class="content-section">
      <h1>LOGIN</h1>
      <br />
      {{ wtf.quick_form(form) }}
      {% if form.email.errors %}
      <div class="invalid-feedback">
        {% for error in messages %}
        <span style="color: red">{{ error }}</span>
        {% endfor %}
      </div>
      {% endif %}
      <p>
        Don't have an account please
        <a href="{{ url_for('auth.register') }}">Signup</a>
      </p>
    </div>
  </div>
</div>
{% endblock %}

app/templates/logout.html
{% extends 'base.html' %} {% import 'bootstrap/utils.html' as utils %}
<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}
{{ utils.flashed_messages() }}
<h1 style="padding-top: 120px; text-align: center">You have been logged out</h1>
<img id="emoji" src="../static/images/emoji.jpeg" alt="emoji" />
{% endblock %}

app/templates/post_job.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
<!-- utils import -->
{% import'bootstrap/utils.html' as utils %}

<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}
<!-- Modal Content -->
<br />
<br />
<br />
<br />
<br />
<br />
<div>
  {{ utils.flashed_messages() }}
  <div class="content-section">
    <h1>Post Job</h1>
    <div class="container">
      {{ wtf.quick_form(form) }}
    </div>
  </div>
</div>

{% endblock %}

app/templates/register.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
<!-- utils import -->
{% import'bootstrap/utils.html' as utils %}

<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}
<!-- Modal Content -->
<div style="background-color: #eaf2f2">
  <div class="form-content">
    {{ utils.flashed_messages() }}
    <div class="content-section">
      <h1>CREATE ACCOUNT</h1>
      <div class="container">
        {{ wtf.quick_form(form) }}
        <p>
          Already have an Account please
          <a href="{{ url_for('auth.login') }}">sign in</a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/review.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
<!-- flash messages -->
{% import 'bootstrap/utils.html' as utils %}

<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="review">
  <h1>Review Form</h1>
  {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/workers.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
<!-- flash messages -->
{% import 'bootstrap/utils.html' as utils %}

<!-- head -->
{% block head %} {% endblock %}

<!-- body -->
{% block content %}

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="container">
  <h1 style="text-align: center">These are people looking for job</h1>
  {% for worker in workers %} {% if worker.employment_status =='Unemployed' or
  worker.employment_status =='None' %}
  <div class="ui cards" style="float: left; margin-right:30px; margin-top:5px">
    <div class="card">
      <div class="content">
        <img
          class="right floated mini ui image"
          src="{{ url_for('static', filename='profile_pics/' + worker.image_file) }}"
        />
        <div class="header">
          <a
            class="header"
            href="{{ url_for('job.user', username = worker.username) }}"
            >{{ worker.username }}</a
          >
        </div>
        <div class="meta">
          <span class="date">Phone Number: {{ worker.phone_no }} </span>
        </div>
        <div class="description">
          <h6 style="color: blue">My Description</h6>
          {{ worker.worker_description }}
        </div>
        <p>Employment Status: {{ worker.employment_status }}</p>
      </div>
      <div class="extra content">
        <div class="ui two buttons">
          <div class="ui basic green button">
            <a href="{{ url_for('job.review', username = worker.username) }}"
              >Review</a
            >
          </div>
          <div class="ui basic red button">
            <a
              class="header"
              href="{{ url_for('job.user', username = worker.username) }}"
              >See Ratings</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- <div
    class="ui special cards"
    style="float:left; margin-right: 30px; margin-top: 0"
  >
    <div class="card">
      <img
        class="ui medium circular image"
        src="{{ url_for('static', filename='profile_pics/' + worker.image_file) }}"
        style="height: 200px"
      />

      <div class="content">
        <a
          class="header"
          href="{{ url_for('job.user', username = worker.username) }}"
          >{{ worker.username }}</a
        >
        <div class="meta">
          <span class="date">Phone Number: {{ worker.phone_no }} </span>
          <p>Employment Status: {{ worker.employment_status }}</p>
        </div>
      </div>
      <div class="extra content">
        <a style="padding-top: 20px">
          <i class="map marker alternate icon"></i>
          {{ worker.location }}
        </a>
        <a href="{{ url_for('job.review', username = worker.username) }}">
          <div
            class="btn "
            style="margin-left: 145px;margin-top: 0;padding-top: 0;background-color: #f19414"
          >
            REVIEW
          </div>
           <button
            
          >
            Review
          </button> -->
  <!-- </a>
      </div>
    </div>
  </div> -->
  {% endif %} {% endfor %}
</div>
{% endblock %}